language: objective-c

branches:
  only:
    - master

xcode_project: JASON.xcodeproj
xcode_scheme: JASONTests
osx_image: xcode9
xcode_sdk: iphonesimulator10.0

script:
  - xcodebuild test -project JASON.xcodeproj -scheme "JASON iOS" -destination "platform=iOS Simulator,name=iPhone 6s"
